In [25]:
import re
import os
import h5py
import time as t
import numpy as np
#import quadpy
#from scipy.special import sph_harm
#from scipy.integrate import tplquad
#from scipy.spatial.transform import Rotation
import scipy as sp
from pyXSteam.XSteam import XSteam

In [26]:
def sprint(sparseMat):
    print(sp.sparse.coo_matrix(sparseMat))

In [27]:
"""lebTest = {
        'x': np.zeros(14),
        'y': np.zeros(14),
        'z': np.zeros(14),
        'w': np.zeros(14)
    }
def test(lebtest):
    print(lebtest["x"])

test(lebTest)"""

'lebTest = {\n        \'x\': np.zeros(14),\n        \'y\': np.zeros(14),\n        \'z\': np.zeros(14),\n        \'w\': np.zeros(14)\n    }\ndef test(lebtest):\n    print(lebtest["x"])\n\ntest(lebTest)'

In [28]:
"""def getLRP(type, start, a, b, v, leb):
    c = 0.0
    np.pi = np.pi
    
    if type == 1:
        a = 1.0
        leb["x"][start] = a
        leb["y"][start] = 0.0
        leb["z"][start] = 0.0
        leb["w"][start] = 4.0 * np.pi * v
        leb["x"][start+1] = -a
        leb["y"][start+1] = 0.0
        leb["z"][start+1] = 0.0
        leb["w"][start+1] = 4.0 * np.pi * v
        leb["x"][start+2] = 0.0
        leb["y"][start+2] = a
        leb["z"][start+2] = 0.0
        leb["w"][start+2] = 4.0 * np.pi * v
        leb["x"][start+3] = 0.0
        leb["y"][start+3] = -a
        leb["z"][start+3] = 0.0
        leb["w"][start+3] = 4.0 * np.pi * v
        leb["x"][start+4] = 0.0
        leb["y"][start+4] = 0.0
        leb["z"][start+4] = a
        leb["w"][start+4] = 4.0 * np.pi * v
        leb["x"][start+5] = 0.0
        leb["y"][start+5] = 0.0
        leb["z"][start+5] = -a
        leb["w"][start+5] = 4.0 * np.pi * v
        start = start + 6

    return leb, start

# Example usage:
degree = 14
start = 6
a = 0.0
b = 0.0
v = 0.0
v = 0.7500000000000000E-1
lebTest = {
        'x': np.zeros(degree),
        'y': np.zeros(degree),
        'z': np.zeros(degree),
        'w': np.zeros(degree)
    }
lebTest, start = getLRP(3, start, a, b, v, lebTest)
print(lebTest)
"""

'def getLRP(type, start, a, b, v, leb):\n    c = 0.0\n    np.pi = np.pi\n    \n    if type == 1:\n        a = 1.0\n        leb["x"][start] = a\n        leb["y"][start] = 0.0\n        leb["z"][start] = 0.0\n        leb["w"][start] = 4.0 * np.pi * v\n        leb["x"][start+1] = -a\n        leb["y"][start+1] = 0.0\n        leb["z"][start+1] = 0.0\n        leb["w"][start+1] = 4.0 * np.pi * v\n        leb["x"][start+2] = 0.0\n        leb["y"][start+2] = a\n        leb["z"][start+2] = 0.0\n        leb["w"][start+2] = 4.0 * np.pi * v\n        leb["x"][start+3] = 0.0\n        leb["y"][start+3] = -a\n        leb["z"][start+3] = 0.0\n        leb["w"][start+3] = 4.0 * np.pi * v\n        leb["x"][start+4] = 0.0\n        leb["y"][start+4] = 0.0\n        leb["z"][start+4] = a\n        leb["w"][start+4] = 4.0 * np.pi * v\n        leb["x"][start+5] = 0.0\n        leb["y"][start+5] = 0.0\n        leb["z"][start+5] = -a\n        leb["w"][start+5] = 4.0 * np.pi * v\n        start = start + 6\n\n    retur

In [29]:
def getLebedevReccurencePoints(type, start, a, b, v, leb):
    c = 0.0
    np.pi = np.pi

    if type == 1:
        a = 1.0
        leb["x"][start] = a
        leb["y"][start] = 0.0
        leb["z"][start] = 0.0
        leb["w"][start] = 4.0 * np.pi * v
        leb["x"][start+1] = -a
        leb["y"][start+1] = 0.0
        leb["z"][start+1] = 0.0
        leb["w"][start+1] = 4.0 * np.pi * v
        leb["x"][start+2] = 0.0
        leb["y"][start+2] = a
        leb["z"][start+2] = 0.0
        leb["w"][start+2] = 4.0 * np.pi * v
        leb["x"][start+3] = 0.0
        leb["y"][start+3] = -a
        leb["z"][start+3] = 0.0
        leb["w"][start+3] = 4.0 * np.pi * v
        leb["x"][start+4] = 0.0
        leb["y"][start+4] = 0.0
        leb["z"][start+4] = a
        leb["w"][start+4] = 4.0 * np.pi * v
        leb["x"][start+5] = 0.0
        leb["y"][start+5] = 0.0
        leb["z"][start+5] = -a
        leb["w"][start+5] = 4.0 * np.pi * v
        start = start + 6

    elif type == 2:
        a = np.sqrt(0.5)
        leb["x"][start] = 0.0
        leb["y"][start] = a
        leb["z"][start] = a
        leb["w"][start] = 4.0 * np.pi * v
        leb["x"][start+1] = 0.0
        leb["y"][start+1] = -a
        leb["z"][start+1] = a
        leb["w"][start+1] = 4.0 * np.pi * v
        leb["x"][start+2] = 0.0
        leb["y"][start+2] = a
        leb["z"][start+2] = -a
        leb["w"][start+2] = 4.0 * np.pi * v
        leb["x"][start+3] = 0.0
        leb["y"][start+3] = -a
        leb["z"][start+3] = -a
        leb["w"][start+3] = 4.0 * np.pi * v
        leb["x"][start+4] = a
        leb["y"][start+4] = 0.0
        leb["z"][start+4] = a
        leb["w"][start+4] = 4.0 * np.pi * v
        leb["x"][start+5] = a
        leb["y"][start+5] = 0.0
        leb["z"][start+5] = -a
        leb["w"][start+5] = 4.0 * np.pi * v
        leb["x"][start+6] = -a
        leb["y"][start+6] = 0.0
        leb["z"][start+6] = a
        leb["w"][start+6] = 4.0 * np.pi * v
        leb["x"][start+7] = -a
        leb["y"][start+7] = 0.0
        leb["z"][start+7] = -a
        leb["w"][start+7] = 4.0 * np.pi * v
        leb["x"][start+8] = a
        leb["y"][start+8] = a
        leb["z"][start+8] = 0.0
        leb["w"][start+8] = 4.0 * np.pi * v
        leb["x"][start+9] = -a
        leb["y"][start+9] = a
        leb["z"][start+9] = 0.0
        leb["w"][start+9] = 4.0 * np.pi * v
        leb["x"][start+10] = a
        leb["y"][start+10] = -a
        leb["z"][start+10] = 0.0
        leb["w"][start+10] = 4.0 * np.pi * v
        leb["x"][start+11] = -a
        leb["y"][start+11] = -a
        leb["z"][start+11] = 0.0
        leb["w"][start+11] = 4.0 * np.pi * v
        start = start + 12

    elif type == 3:
        a = np.sqrt(1.0 / 3.0)
        leb["x"][start] = a
        leb["y"][start] = a
        leb["z"][start] = a
        leb["w"][start] = 4.0 * np.pi * v
        leb["x"][start+1] = -a
        leb["y"][start+1] = a
        leb["z"][start+1] = a
        leb["w"][start+1] = 4.0 * np.pi * v
        leb["x"][start+2] = a
        leb["y"][start+2] = -a
        leb["z"][start+2] = a
        leb["w"][start+2] = 4.0 * np.pi * v
        leb["x"][start+3] = a
        leb["y"][start+3] = a
        leb["z"][start+3] = -a
        leb["w"][start+3] = 4.0 * np.pi * v
        leb["x"][start+4] = -a
        leb["y"][start+4] = -a
        leb["z"][start+4] = a
        leb["w"][start+4] = 4.0 * np.pi * v
        leb["x"][start+5] = a
        leb["y"][start+5] = -a
        leb["z"][start+5] = -a
        leb["w"][start+5] = 4.0 * np.pi * v
        leb["x"][start+6] = -a
        leb["y"][start+6] = a
        leb["z"][start+6] = -a
        leb["w"][start+6] = 4.0 * np.pi * v
        leb["x"][start+7] = -a
        leb["y"][start+7] = -a
        leb["z"][start+7] = -a
        leb["w"][start+7] = 4.0 * np.pi * v
        start = start + 8

    elif type == 4:
        #%/* In this case A is inputed */
        b = np.sqrt(1.0 - 2.0*a*a)
        leb["x"][start] = a
        leb["y"][start] = a
        leb["z"][start] = b
        leb["w"][start] = 4.0*np.pi*v
        leb["x"][start+1] = -a
        leb["y"][start+1] = a
        leb["z"][start+1] = b
        leb["w"][start+1] = 4.0*np.pi*v
        leb["x"][start+2] = a
        leb["y"][start+2] = -a
        leb["z"][start+2] = b
        leb["w"][start+2] = 4.0*np.pi*v
        leb["x"][start+3] = a
        leb["y"][start+3] = a
        leb["z"][start+3] = -b
        leb["w"][start+3] = 4.0*np.pi*v
        leb["x"][start+4] = -a
        leb["y"][start+4] = -a
        leb["z"][start+4] = b
        leb["w"][start+4] = 4.0*np.pi*v
        leb["x"][start+5] = -a
        leb["y"][start+5] = a
        leb["z"][start+5] = -b
        leb["w"][start+5] = 4.0*np.pi*v
        leb["x"][start+6] = a
        leb["y"][start+6] = -a
        leb["z"][start+6] = -b
        leb["w"][start+6] = 4.0*np.pi*v
        leb["x"][start+7] = -a
        leb["y"][start+7] = -a
        leb["z"][start+7] = -b
        leb["w"][start+7] = 4.0*np.pi*v
        leb["x"][start+8] = -a
        leb["y"][start+8] = b
        leb["z"][start+8] = a
        leb["w"][start+8] = 4.0*np.pi*v
        leb["x"][start+9] = a
        leb["y"][start+9] = -b
        leb["z"][start+9] = a
        leb["w"][start+9] = 4.0*np.pi*v
        leb["x"][start+10] = a
        leb["y"][start+10] = b
        leb["z"][start+10] = -a
        leb["w"][start+10] = 4.0*np.pi*v
        leb["x"][start+11] = -a
        leb["y"][start+11] = -b
        leb["z"][start+11] = a
        leb["w"][start+11] = 4.0*np.pi*v
        leb["x"][start+12] = -a
        leb["y"][start+12] = b
        leb["z"][start+12] = -a
        leb["w"][start+12] = 4.0*np.pi*v
        leb["x"][start+13] = a
        leb["y"][start+13] = -b
        leb["z"][start+13] = -a
        leb["w"][start+13] = 4.0*np.pi*v
        leb["x"][start+14] = -a
        leb["y"][start+14] = -b
        leb["z"][start+14] = -a
        leb["w"][start+14] = 4.0*np.pi*v
        leb["x"][start+15] = a
        leb["y"][start+15] = b
        leb["z"][start+15] = a
        leb["w"][start+15] = 4.0*np.pi*v
        leb["x"][start+16] = b
        leb["y"][start+16] = a
        leb["z"][start+16] = a
        leb["w"][start+16] = 4.0*np.pi*v
        leb["x"][start+17] = -b
        leb["y"][start+17] = a
        leb["z"][start+17] = a
        leb["w"][start+17] = 4.0*np.pi*v
        leb["x"][start+18] = b
        leb["y"][start+18] = -a
        leb["z"][start+18] = a
        leb["w"][start+18] = 4.0*np.pi*v
        leb["x"][start+19] = b
        leb["y"][start+19] = a
        leb["z"][start+19] = -a
        leb["w"][start+19] = 4.0*np.pi*v
        leb["x"][start+20] = -b
        leb["y"][start+20] = -a
        leb["z"][start+20] = a
        leb["w"][start+20] = 4.0*np.pi*v
        leb["x"][start+21] = -b
        leb["y"][start+21] = a
        leb["z"][start+21] = -a
        leb["w"][start+21] = 4.0*np.pi*v
        leb["x"][start+22] = b
        leb["y"][start+22] = -a
        leb["z"][start+22] = -a
        leb["w"][start+22] = 4.0*np.pi*v
        leb["x"][start+23] = -b
        leb["y"][start+23] = -a
        leb["z"][start+23] = -a
        leb["w"][start+23] = 4.0*np.pi*v
        start = start + 24
    
    elif type == 5:
        #%/* A is inputed in this case as well*/
        b = np.sqrt(1-a*a)
        leb["x"][start] = a
        leb["y"][start] = b
        leb["z"][start] = 0.0
        leb["w"][start] = 4.0*np.pi*v
        leb["x"][start+1] = -a
        leb["y"][start+1] = b
        leb["z"][start+1] = 0.0
        leb["w"][start+1] = 4.0*np.pi*v
        leb["x"][start+2] = a
        leb["y"][start+2] = -b
        leb["z"][start+2] = 0.0
        leb["w"][start+2] = 4.0*np.pi*v
        leb["x"][start+3] = -a
        leb["y"][start+3] = -b
        leb["z"][start+3] = 0.0
        leb["w"][start+3] = 4.0*np.pi*v
        leb["x"][start+4] = b
        leb["y"][start+4] = a
        leb["z"][start+4] = 0.0
        leb["w"][start+4] = 4.0*np.pi*v
        leb["x"][start+5] = -b
        leb["y"][start+5] = a
        leb["z"][start+5] = 0.0
        leb["w"][start+5] = 4.0*np.pi*v
        leb["x"][start+6] = b
        leb["y"][start+6] = -a
        leb["z"][start+6] = 0.0
        leb["w"][start+6] = 4.0*np.pi*v
        leb["x"][start+7] = -b
        leb["y"][start+7] = -a
        leb["z"][start+7] = 0.0
        leb["w"][start+7] = 4.0*np.pi*v
        leb["x"][start+8] = a
        leb["y"][start+8] = 0.0
        leb["z"][start+8] = b
        leb["w"][start+8] = 4.0*np.pi*v
        leb["x"][start+9] = -a
        leb["y"][start+9] = 0.0
        leb["z"][start+9] = b
        leb["w"][start+9] = 4.0*np.pi*v
        leb["x"][start+10] = a
        leb["y"][start+10] = 0.0
        leb["z"][start+10] = -b
        leb["w"][start+10] = 4.0*np.pi*v
        leb["x"][start+11] = -a
        leb["y"][start+11] = 0.0
        leb["z"][start+11] = -b
        leb["w"][start+11] = 4.0*np.pi*v
        leb["x"][start+12] = b
        leb["y"][start+12] = 0.0
        leb["z"][start+12] = a
        leb["w"][start+12] = 4.0*np.pi*v
        leb["x"][start+13] = -b
        leb["y"][start+13] = 0.0
        leb["z"][start+13] = a
        leb["w"][start+13] = 4.0*np.pi*v
        leb["x"][start+14] = b
        leb["y"][start+14] = 0.0
        leb["z"][start+14] = -a
        leb["w"][start+14] = 4.0*np.pi*v
        leb["x"][start+15] = -b
        leb["y"][start+15] = 0.0
        leb["z"][start+15] = -a
        leb["w"][start+15] = 4.0*np.pi*v
        leb["x"][start+16] = 0.0
        leb["y"][start+16] = a
        leb["z"][start+16] = b
        leb["w"][start+16] = 4.0*np.pi*v
        leb["x"][start+17] = 0.0
        leb["y"][start+17] = -a
        leb["z"][start+17] = b
        leb["w"][start+17] = 4.0*np.pi*v
        leb["x"][start+18] = 0.0
        leb["y"][start+18] = a
        leb["z"][start+18] = -b
        leb["w"][start+18] = 4.0*np.pi*v
        leb["x"][start+19] = 0.0
        leb["y"][start+19] = -a
        leb["z"][start+19] = -b
        leb["w"][start+19] = 4.0*np.pi*v
        leb["x"][start+20] = 0.0
        leb["y"][start+20] = b
        leb["z"][start+20] = a
        leb["w"][start+20] = 4.0*np.pi*v
        leb["x"][start+21] = 0.0
        leb["y"][start+21] = -b
        leb["z"][start+21] = a
        leb["w"][start+21] = 4.0*np.pi*v
        leb["x"][start+22] = 0.0
        leb["y"][start+22] = b
        leb["z"][start+22] = -a
        leb["w"][start+22] = 4.0*np.pi*v
        leb["x"][start+23] = 0.0
        leb["y"][start+23] = -b
        leb["z"][start+23] = -a
        leb["w"][start+23] = 4.0*np.pi*v
        start = start + 24
    
    elif type == 6:
        #%/* both A and B are inputed in this case */
        c = np.sqrt(1.0 - a*a - b*b)
        leb["x"][start] = a
        leb["y"][start] = b
        leb["z"][start] = c
        leb["w"][start] = 4.0*np.pi*v
        leb["x"][start+1] = -a
        leb["y"][start+1] = b
        leb["z"][start+1] = c
        leb["w"][start+1] = 4.0*np.pi*v
        leb["x"][start+2] = a
        leb["y"][start+2] = -b
        leb["z"][start+2] = c
        leb["w"][start+2] = 4.0*np.pi*v
        leb["x"][start+3] = a
        leb["y"][start+3] = b
        leb["z"][start+3] = -c
        leb["w"][start+3] = 4.0*np.pi*v
        leb["x"][start+4] = -a
        leb["y"][start+4] = -b
        leb["z"][start+4] = c
        leb["w"][start+4] = 4.0*np.pi*v
        leb["x"][start+5] = a
        leb["y"][start+5] = -b
        leb["z"][start+5] = -c
        leb["w"][start+5] = 4.0*np.pi*v
        leb["x"][start+6] = -a
        leb["y"][start+6] = b
        leb["z"][start+6] = -c
        leb["w"][start+6] = 4.0*np.pi*v
        leb["x"][start+7] = -a
        leb["y"][start+7] = -b
        leb["z"][start+7] = -c
        leb["w"][start+7] = 4.0*np.pi*v
        leb["x"][start+8] = b
        leb["y"][start+8] = a
        leb["z"][start+8] = c
        leb["w"][start+8] = 4.0*np.pi*v
        leb["x"][start+9] = -b
        leb["y"][start+9] = a
        leb["z"][start+9] = c
        leb["w"][start+9] = 4.0*np.pi*v
        leb["x"][start+10] = b
        leb["y"][start+10] = -a
        leb["z"][start+10] = c
        leb["w"][start+10] = 4.0*np.pi*v
        leb["x"][start+11] = b
        leb["y"][start+11] = a
        leb["z"][start+11] = -c
        leb["w"][start+11] = 4.0*np.pi*v
        leb["x"][start+12] = -b
        leb["y"][start+12] = -a
        leb["z"][start+12] = c
        leb["w"][start+12] = 4.0*np.pi*v
        leb["x"][start+13] = b
        leb["y"][start+13] = -a
        leb["z"][start+13] = -c
        leb["w"][start+13] = 4.0*np.pi*v
        leb["x"][start+14] = -b
        leb["y"][start+14] = a
        leb["z"][start+14] = -c
        leb["w"][start+14] = 4.0*np.pi*v
        leb["x"][start+15] = -b
        leb["y"][start+15] = -a
        leb["z"][start+15] = -c
        leb["w"][start+15] = 4.0*np.pi*v
        leb["x"][start+16] = c
        leb["y"][start+16] = a
        leb["z"][start+16] = b
        leb["w"][start+16] = 4.0*np.pi*v
        leb["x"][start+17] = -c
        leb["y"][start+17] = a
        leb["z"][start+17] = b
        leb["w"][start+17] = 4.0*np.pi*v
        leb["x"][start+18] = c
        leb["y"][start+18] = -a
        leb["z"][start+18] = b
        leb["w"][start+18] = 4.0*np.pi*v
        leb["x"][start+19] = c
        leb["y"][start+19] = a
        leb["z"][start+19] = -b
        leb["w"][start+19] = 4.0*np.pi*v
        leb["x"][start+20] = -c
        leb["y"][start+20] = -a
        leb["z"][start+20] = b
        leb["w"][start+20] = 4.0*np.pi*v
        leb["x"][start+21] = c
        leb["y"][start+21] = -a
        leb["z"][start+21] = -b
        leb["w"][start+21] = 4.0*np.pi*v
        leb["x"][start+22] = -c
        leb["y"][start+22] = a
        leb["z"][start+22] = -b
        leb["w"][start+22] = 4.0*np.pi*v
        leb["x"][start+23] = -c
        leb["y"][start+23] = -a
        leb["z"][start+23] = -b
        leb["w"][start+23] = 4.0*np.pi*v
        leb["x"][start+24] = c
        leb["y"][start+24] = b
        leb["z"][start+24] = a
        leb["w"][start+24] = 4.0*np.pi*v
        leb["x"][start+25] = -c
        leb["y"][start+25] = b
        leb["z"][start+25] = a
        leb["w"][start+25] = 4.0*np.pi*v
        leb["x"][start+26] = c
        leb["y"][start+26] = -b
        leb["z"][start+26] = a
        leb["w"][start+26] = 4.0*np.pi*v
        leb["x"][start+27] = c
        leb["y"][start+27] = b
        leb["z"][start+27] = -a
        leb["w"][start+27] = 4.0*np.pi*v
        leb["x"][start+28] = -c
        leb["y"][start+28] = -b
        leb["z"][start+28] = a
        leb["w"][start+28] = 4.0*np.pi*v
        leb["x"][start+29] = c
        leb["y"][start+29] = -b
        leb["z"][start+29] = -a
        leb["w"][start+29] = 4.0*np.pi*v
        leb["x"][start+30] = -c
        leb["y"][start+30] = b
        leb["z"][start+30] = -a
        leb["w"][start+30] = 4.0*np.pi*v
        leb["x"][start+31] = -c
        leb["y"][start+31] = -b
        leb["z"][start+31] = -a
        leb["w"][start+31] = 4.0*np.pi*v
        leb["x"][start+32] = a
        leb["y"][start+32] = c
        leb["z"][start+32] = b
        leb["w"][start+32] = 4.0*np.pi*v
        leb["x"][start+33] = -a
        leb["y"][start+33] = c
        leb["z"][start+33] = b
        leb["w"][start+33] = 4.0*np.pi*v
        leb["x"][start+34] = a
        leb["y"][start+34] = -c
        leb["z"][start+34] = b
        leb["w"][start+34] = 4.0*np.pi*v
        leb["x"][start+35] = a
        leb["y"][start+35] = c
        leb["z"][start+35] = -b
        leb["w"][start+35] = 4.0*np.pi*v
        leb["x"][start+36] = -a
        leb["y"][start+36] = -c
        leb["z"][start+36] = b
        leb["w"][start+36] = 4.0*np.pi*v
        leb["x"][start+37] = a
        leb["y"][start+37] = -c
        leb["z"][start+37] = -b
        leb["w"][start+37] = 4.0*np.pi*v
        leb["x"][start+38] = -a
        leb["y"][start+38] = c
        leb["z"][start+38] = -b
        leb["w"][start+38] = 4.0*np.pi*v
        leb["x"][start+39] = -a
        leb["y"][start+39] = -c
        leb["z"][start+39] = -b
        leb["w"][start+39] = 4.0*np.pi*v
        leb["x"][start+40] = b
        leb["y"][start+40] = c
        leb["z"][start+40] = a
        leb["w"][start+40] = 4.0*np.pi*v
        leb["x"][start+41] = -b
        leb["y"][start+41] = c
        leb["z"][start+41] = a
        leb["w"][start+41] = 4.0*np.pi*v
        leb["x"][start+42] = b
        leb["y"][start+42] = -c
        leb["z"][start+42] = a
        leb["w"][start+42] = 4.0*np.pi*v
        leb["x"][start+43] = b
        leb["y"][start+43] = c
        leb["z"][start+43] = -a
        leb["w"][start+43] = 4.0*np.pi*v
        leb["x"][start+44] = -b
        leb["y"][start+44] = -c
        leb["z"][start+44] = a
        leb["w"][start+44] = 4.0*np.pi*v
        leb["x"][start+45] = b
        leb["y"][start+45] = -c
        leb["z"][start+45] = -a
        leb["w"][start+45] = 4.0*np.pi*v
        leb["x"][start+46] = -b
        leb["y"][start+46] = c
        leb["z"][start+46] = -a
        leb["w"][start+46] = 4.0*np.pi*v
        leb["x"][start+47] = -b
        leb["y"][start+47] = -c
        leb["z"][start+47] = -a
        leb["w"][start+47] = 4.0*np.pi*v
        start = start + 48

    else:
        raise ValueError('Bad grid order')

    return leb, start


In [30]:
degree = 14
start = 0
a = 0.0
b = 0.0
c = 0.0

leb_tmp = {
        'x': np.zeros(degree),
        'y': np.zeros(degree),
        'z': np.zeros(degree),
        'w': np.zeros(degree)
    }
v = 0.6666666666666667E-1
leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
v = 0.7500000000000000E-1
print("start = ", start, "\n", leb_tmp, "\nsize =", np.size(leb_tmp))
#leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)
#leb_tmp

start =  6 
 {'x': array([ 1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.]), 'y': array([ 0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.]), 'z': array([ 0.,  0.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.]), 'w': array([0.83775804, 0.83775804, 0.83775804, 0.83775804, 0.83775804,
       0.83775804, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])} 
size = 1


In [31]:
def getLebedevSphere(degree):
    # Function implementation (as shown in the previous response)

    leb_tmp = {
        'x': np.zeros(degree),
        'y': np.zeros(degree),
        'z': np.zeros(degree),
        'w': np.zeros(degree),
        'n': degree
    }

    start = 0
    a = 0.0
    b = 0.0
    c = 0.0
    v = 0.0

    if degree == 6:
        v = 0.6666666666666667E-1
        leb_tmp, start = getLebedevReccurencePoints(1, start, a, b, v, leb_tmp)

    elif degree == 14:
        v = 0.6666666666666667E-1
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.7500000000000000E-1
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)

    elif degree == 26:
        v = 0.4761904761904762E-1
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.3809523809523810E-1
        leb_tmp, start = getLebedevReccurencePoints(2,start,a,b,v,leb_tmp)
        v = 0.3214285714285714E-1
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)

    elif degree == 38:
        v = 0.9523809523809524E-2
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.3214285714285714E-1
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)
        a = 0.4597008433809831E+0
        v = 0.2857142857142857E-1
        leb_tmp, start = getLebedevReccurencePoints(5,start,a,b,v,leb_tmp)

    elif degree == 50:
        v = 0.1269841269841270E-1
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.2257495590828924E-1
        leb_tmp, start = getLebedevReccurencePoints(2,start,a,b,v,leb_tmp)
        v = 0.2109375000000000E-1
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)
        a = 0.3015113445777636E+0
        v = 0.2017333553791887E-1
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)

    elif degree == 74:
        v = 0.5130671797338464E-3
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.1660406956574204E-1
        leb_tmp, start = getLebedevReccurencePoints(2,start,a,b,v,leb_tmp)
        v = -0.2958603896103896E-1
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)
        a = 0.4803844614152614E+0
        v = 0.2657620708215946E-1
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)
        a = 0.3207726489807764E+0
        v = 0.1652217099371571E-1
        leb_tmp, start = getLebedevReccurencePoints(5,start,a,b,v,leb_tmp)

    elif degree == 86:
        v = 0.1154401154401154E-1
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.1194390908585628E-1
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)
        a = 0.3696028464541502E+0
        v = 0.1111055571060340E-1
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)
        a = 0.6943540066026664E+0
        v = 0.1187650129453714E-1
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)
        a = 0.3742430390903412E+0
        v = 0.1181230374690448E-1
        leb_tmp, start = getLebedevReccurencePoints(5,start,a,b,v,leb_tmp)

    elif degree == 110:
        v = 0.3828270494937162E-2
        leb_tmp, start = getLebedevReccurencePoints(1,start,a,b,v,leb_tmp)
        v = 0.9793737512487512E-2
        leb_tmp, start = getLebedevReccurencePoints(3,start,a,b,v,leb_tmp)
        a = 0.1851156353447362E+0
        v = 0.8211737283191111E-2
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)
        a = 0.6904210483822922E+0
        v = 0.9942814891178103E-2
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)
        a = 0.3956894730559419E+0
        v = 0.9595471336070963E-2
        leb_tmp, start = getLebedevReccurencePoints(4,start,a,b,v,leb_tmp)
        a = 0.4783690288121502E+0
        v = 0.9694996361663028E-2
        leb_tmp, start = getLebedevReccurencePoints(5,start,a,b,v,leb_tmp)
    else:
         raise ValueError('Angular grid unrecognized, choices are 6, 14, 26, 38, 50, 74, 86, 110')
        
    return leb_tmp


In [32]:
getLebedevSphere(110)["y"]

array([ 0.        ,  0.        ,  1.        , -1.        ,  0.        ,
        0.        ,  0.57735027,  0.57735027, -0.57735027,  0.57735027,
       -0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.18511564,
        0.18511564, -0.18511564,  0.18511564, -0.18511564,  0.18511564,
       -0.18511564, -0.18511564,  0.96512404, -0.96512404,  0.96512404,
       -0.96512404,  0.96512404, -0.96512404, -0.96512404,  0.96512404,
        0.18511564,  0.18511564, -0.18511564,  0.18511564, -0.18511564,
        0.18511564, -0.18511564, -0.18511564,  0.69042105,  0.69042105,
       -0.69042105,  0.69042105, -0.69042105,  0.69042105, -0.69042105,
       -0.69042105,  0.21595729, -0.21595729,  0.21595729, -0.21595729,
        0.21595729, -0.21595729, -0.21595729,  0.21595729,  0.69042105,
        0.69042105, -0.69042105,  0.69042105, -0.69042105,  0.69042105,
       -0.69042105, -0.69042105,  0.39568947,  0.39568947, -0.39568947,
        0.39568947, -0.39568947,  0.39568947, -0.39568947, -0.39

In [33]:
def initPWR_like():
    #global global_g
    with h5py.File("..//00.Lib/initPWR_like.h5", "w") as hdf:
        g  = hdf.create_group("g")
        th = hdf.create_group("th")
        fr = hdf.create_group("fr")

        #group.attrs["nz"] = 10
        #global_g = group

        # Input fuel rod geometry and nodalization
        g_nz = 10  # number of axial nodes
        g.create_dataset("nz", data=g_nz)

        g_fuel_rIn = 0  # inner fuel radius (m)
        g_fuel_rOut = 4.12e-3  # outer fuel radius (m)
        g_fuel_nr = 20  # number of radial nodes in fuel
        g_fuel = g.create_group("fuel")
        g_fuel.create_dataset("rIn",  data=g_fuel_rIn)
        g_fuel.create_dataset("rOut", data=g_fuel_rOut)
        g_fuel.create_dataset("nr",   data=g_fuel_nr)

        g_clad_rIn = 4.22e-3  # inner clad radius (m)
        g_clad_rOut = 4.75e-3  # outer clad radius (m)
        g_clad_nr = 5
        g_clad = g.create_group("clad")
        g_clad.create_dataset("rIn",  data=g_clad_rIn)
        g_clad.create_dataset("rOut", data=g_clad_rOut)
        g_clad.create_dataset("nr",   data=g_clad_nr)

        g_cool_pitch = 13.3e-3  # square unit cell pitch (m)
        g_cool_rOut = np.sqrt(g_cool_pitch**2 / np.pi)  # equivalent radius of the unit cell (m)
        g_cool = g.create_group("cool")
        g_cool.create_dataset("pitch", data=g_cool_pitch)
        g_cool.create_dataset("rOut",  data=g_cool_rOut)

        g_dz0 = 0.3 * np.ones(g_nz)  # height of the node (m)
        g_dzGasPlenum = 0.2  # height of the fuel rod gas plenum assuming it is empty (m)
        g.create_dataset("dz0", data = g_dz0)
        g.create_dataset("dzGasPlenum", data = g_dzGasPlenum)

        # Input average power rating in fuel
        th_qLHGR0 = np.array([  [0, 10, 1e20],  # time (s)
                                [200e2, 200e2, 200e2]   ])  # linear heat generation rate (W/m)
        th.create_dataset("qLHGR0", data = th_qLHGR0)

        # Input fuel rod parameters
        fr_clad_fastFlux = np.array([   [0, 10, 1e20],  # time (s)
                                        [1e13, 1e13, 1e13]  ])  # fast flux in cladding (1/cm2-s)
        fr_clad = fr.create_group("clad")
        fr_clad.create_dataset("fastFlux", data = fr_clad_fastFlux)

        fr_fuel_FGR = np.array([[0, 10, 1e20],  # time (s)
                                [0.03, 0.03, 0.03]])  # fission gas release (-)
        fr_fuel = fr.create_group("fuel")
        fr_fuel.create_dataset("FGR", data = fr_fuel_FGR)

        fr_ingas_Tplenum = 533  # fuel rod gas plenum temperature (K)
        fr_ingas_p0 = 1  # as-fabricated helium pressure inside fuel rod (MPa)
        fr_fuel_por = 0.05 * np.ones((g_nz, g_fuel_nr))  # initial fuel porosity (-)
        fr_ingas = fr.create_group("ingas")
        fr_ingas.create_dataset("Tplenum", data = fr_ingas_Tplenum)
        fr_ingas.create_dataset("p0",      data = fr_ingas_p0)
        fr_fuel.create_dataset("por",      data = fr_fuel_por)

        # Input channel geometry
        g_aFlow = 8.914e-5 * np.ones(g_nz)  # flow area (m2)
        g.create_dataset("aFlow", data = g_aFlow)

        # Input channel parameters
        th_mdot0_ = np.array([  [0, 10, 1000],  # time (s)
                                [0.3, 0.3, 0.3]])  # flowrate (kg/s) 0.3
        th_p0 = 16  # coolant pressure (MPa)
        th_T0 = 533.0  # inlet temperature (K)
        th.create_dataset("mdot0", data = th_mdot0_)
        th.create_dataset("p0",    data = th_p0)
        th.create_dataset("T0",    data = th_T0)

        # Initialize fuel geometry
        g_fuel_dr0 = (g_fuel_rOut - g_fuel_rIn) / (g_fuel_nr - 1)  # fuel node radial thickness (m)
        g_fuel_r0 = np.arange(g_fuel_rIn, g_fuel_rOut + g_fuel_dr0, g_fuel_dr0)  # fuel node radius (m)
        g_fuel_r0_ = np.concatenate(([g_fuel_rIn], np.interp(np.arange(1.5, g_fuel_nr + 0.5), np.arange(1, g_fuel_nr + 1),
                                                                    g_fuel_r0), [g_fuel_rOut]))  # fuel node boundary (m)
        g_fuel_a0_ = np.transpose(np.tile(2*np.pi*g_fuel_r0_[:, None], g_nz)) * np.tile(g_dz0[:, None], (1, g_fuel_nr + 1))  # XS area of fuel node boundary (m2)
        g_fuel_v0 = np.transpose(np.tile(np.pi*np.diff(g_fuel_r0_**2)[:, None], g_nz)) * np.tile(g_dz0[:, None], (1, g_fuel_nr))  # fuel node volume (m3)
        g_fuel_vFrac = (g_fuel_rOut**2 - g_fuel_rIn**2) / g_cool_rOut**2
        g_fuel.create_dataset("dr0",   data = g_fuel_dr0)
        g_fuel.create_dataset("r0",    data = g_fuel_r0)
        g_fuel.create_dataset("r0_",   data = g_fuel_r0_)
        g_fuel.create_dataset("a0_",   data = g_fuel_a0_)
        g_fuel.create_dataset("v0",    data = g_fuel_v0)
        g_fuel.create_dataset("vFrac", data = g_fuel_vFrac)

        # Initialize clad geometry
        g_clad_dr0 = (g_clad_rOut - g_clad_rIn) / (g_clad_nr - 1)  # clad node radial thickness (m)
        g_clad_r0 = np.arange(g_clad_rIn, g_clad_rOut + g_clad_dr0, g_clad_dr0)  # clad node radius (m)
        g_clad_r0_ = np.concatenate(([g_clad_rIn], np.interp(np.arange(1.5, g_clad_nr + 0.5), np.arange(1, g_clad_nr + 1), 
                                                                    g_clad_r0), [g_clad_rOut]))  # clad node boundary (m)
        g_clad_a0_ = np.transpose(np.tile(2 * np.pi * g_clad_r0_[:, None], g_nz)) * np.tile(g_dz0[:, None], (1, g_clad_nr + 1))  # XS area of clad node boundary (m2)
        g_clad_v0 = np.transpose(np.tile(np.pi*np.diff(g_clad_r0_**2)[:, None], g_nz)) * np.tile(g_dz0[:, None], (1, g_clad_nr))  # clad node volume (m3)
        g_clad_vFrac = (g_clad_rOut**2 - g_clad_rIn**2) / g_cool_rOut**2
        g_clad.create_dataset("dr0",   data = g_clad_dr0)
        g_clad.create_dataset("r0",    data = g_clad_r0)
        g_clad.create_dataset("r0_",   data = g_clad_r0_)
        g_clad.create_dataset("a0_",   data = g_clad_a0_)
        g_clad.create_dataset("v0",    data = g_clad_v0)
        g_clad.create_dataset("vFrac", data = g_clad_vFrac)

        # Initialize gap geometry
        dimensions = tuple(range(1, g_nz+1))
        g_gap_dr0 = (g_clad_rIn - g_fuel_rOut) * np.ones(dimensions)   # initial cold gap (m)
        g_gap_r0_ = (g_clad_rIn + g_fuel_rOut) / 2  # average gap radius (m)
        g_gap_a0_ = (2 * np.pi * g_gap_r0_ * np.ones((g_nz, 1))) * g_dz0  # XS area of the mid-gap (m2)
        g_gap_vFrac = (g_clad_rIn**2 - g_fuel_rOut**2) / g_cool_rOut**2
        g_gap = g.create_group("gap")
        g_gap.create_dataset("dr0",   data = g_gap_dr0.flatten())
        g_gap.create_dataset("r0_",   data = g_gap_r0_)
        g_gap.create_dataset("a0_",   data = g_gap_a0_)
        g_gap.create_dataset("vFrac", data = g_gap_vFrac)

        # Initialize as-fabricated inner volumes and gas amount
        g_vGasPlenum = g_dzGasPlenum * np.pi * g_clad_rIn**2  # gas plenum volume (m3)
        g_vGasGap = g_dz0 * np.pi * (g_clad_rIn**2 - g_fuel_rOut**2)  # gas gap volume (m3)
        g_vGasCentralVoid = g_dz0 * np.pi * g_fuel_rIn**2  # gas central void volume (m3)
        fr_ingas_muHe0 = fr_ingas_p0 * (g_vGasPlenum + np.sum(g_vGasGap + g_vGasCentralVoid)) / (8.31e-6 * 293)  # as-fabricated gas amount inside fuel rod (mole)
        g.create_dataset("vGasPlenum",      data = g_vGasPlenum)
        g.create_dataset("vGasGap",         data = g_vGasGap)
        g.create_dataset("vGasCentralVoid", data = g_vGasCentralVoid)
        fr_ingas.create_dataset("muHe0",    data = fr_ingas_muHe0)

        # Initialize gas gap status
        g_gap_open = np.ones(g_nz)
        g_gap_clsd = np.zeros(g_nz)
        g_gap.create_dataset("open", data = g_gap_open)
        g_gap.create_dataset("clsd", data = g_gap_clsd)

        # Initialize fuel and clad total deformation components
        fr_fuel_eps0 = np.zeros((3, g_nz, g_fuel_nr))
        fr_clad_eps0 = np.zeros((3, g_nz, g_clad_nr))
        fuel_eps0 = fr_fuel.create_group("eps0")
        clad_eps0 = fr_clad.create_group("eps0")
        for i in range(3):
            fr_fuel_eps0[i] = np.zeros((g_nz, g_fuel_nr))
            fr_clad_eps0[i] = np.zeros((g_nz, g_clad_nr))
            fuel_eps0.create_dataset(f"eps0(0,{i})", data = fr_fuel_eps0[i])
            clad_eps0.create_dataset(f"eps0(0,{i})", data = fr_clad_eps0[i])

        # Initialize flow channel geometry
        g_volFlow = g_aFlow * g_dz0  # volume of node (m3)
        g_areaHX = 2 * np.pi * g_clad_rOut * g_dz0  # heat exchange area(m2)(m2)
        g_dHyd = 4 * g_volFlow / g_areaHX  # hydraulic diameter (m)
        g_cool_vFrac = (g_cool_rOut**2 - g_clad_rOut**2) / g_cool_rOut**2
        g.create_dataset("volFlow",    data = g_volFlow)
        g.create_dataset("areaHX",     data = g_areaHX)
        g.create_dataset("dHyd",       data = g_dHyd)
        g_cool.create_dataset("vFrac", data = g_cool_vFrac)

        # Initialize thermal hydraulic parameters
        # Path to steam-water properties
        steamTable = XSteam(XSteam.UNIT_SYSTEM_MKS)
        th_h0 = steamTable.h_pt(th_p0 / 10, th_T0 - 273) * 1e3  # water enthalpy at core inlet (J/kg)
        th_h = np.ones(g_nz) * th_h0  # initial enthalpy in nodes (kJ/kg)
        th_p = np.ones(g_nz) * th_p0  # initial pressure in nodes (MPa)
        th.create_dataset("h0", data = th_h0)
        th.create_dataset("h", data = th_h)
        th.create_dataset("p", data = th_p)

def readPWR_like(input_keyword):
    # Define the mapping of input keyword to group name
    group_mapping = {
        "fr": "fr",
        "g": "g",
        "th": "th"
    }
    # Define the dictionary to store the datasets
    data = {}
    # Open the HDF5 file
    with h5py.File("..//00.Lib/initPWR_like.h5", "r") as file:
        # Get the group name based on the input keyword
        group_name = group_mapping.get(input_keyword)
        if group_name is not None:
            # Get the group
            group = file[group_name]
            # Iterate over the dataset names in the group
            for dataset_name in group.keys():
                # Read the dataset
                dataset = group[dataset_name]
                # Check if the dataset is a struct
                if isinstance(dataset, h5py.Group):
                    # Create a dictionary to store the struct fields
                    struct_data = {}
                    # Iterate over the fields in the struct
                    for field_name in dataset.keys():
                        # Read the field dataset
                        field_dataset = np.array(dataset[field_name])
                        # Store the field dataset in the struct dictionary
                        struct_data[field_name] = field_dataset
                    # Store the struct data in the main data dictionary
                    data[dataset_name] = struct_data
                else:
                    # Read the dataset as a regular array
                    dataset_array = np.array(dataset)
                    # Store the dataset array in the dictionary
                    data[dataset_name] = dataset_array

    return data

In [34]:
def hdf2dict(file_name):
    # Define the dictionary to store the datasets
    data = {}
    #file_name = 'macro421_UO2_03__900K.h5'
    with h5py.File("..//02.Macro.XS.421g/" + file_name, "r") as file:
        # Iterate over the dataset names in the group
        for dataset_name in file.keys():
            # Read the dataset
            dataset = file[dataset_name]
            # Check if the dataset is a struct
            if isinstance(dataset, h5py.Group):
                # Create a dictionary to store the struct fields
                struct_data = {}
                # Iterate over the fields in the struct
                for field_name in dataset.keys():
                    # Read the field dataset
                    field_dataset = np.array(dataset[field_name])
                    # Store the field dataset in the struct dictionary
                    struct_data[field_name] = field_dataset
                # Store the struct data in the main data dictionary
                data[dataset_name] = struct_data
            else:
                # Read the dataset as a regular array
                dataset_array = np.array(dataset)
                # Store the dataset array in the dictionary
                data[dataset_name] = dataset_array
    return data

In [35]:
# Start stopwatch

start_time = t.time()

# Global variables with geometry parameters, total cross section, and number of groups
#global g, SigT, ng
# input and initialize the geometry of the PWR unit cell (the function is in '..\00.Lib')
lib_path = os.path.join('..', '00.Lib')
file_path_PWR = os.path.join(lib_path, 'initPWR_like.h5')

if not os.path.exists(file_path_PWR):
    # File doesn't exist, call initPWR_like() function
    initPWR_like()
# Read in the necessary data struct. Options: {fr, g, th}
g = readPWR_like("g")
#--------------------------------------------------------------------------
# Path to macrosconp.pic cross section data:
#import os
#path_to_data = os.path.join('..', '02.Macro.XS.421g')
# Fill the structures fuel, clad, and cool with the cross-section data
fuel = hdf2dict('macro421_UO2_03__900K.h5')  # INPUT
print(f"File 'macro421_UO2_03__900K.h5' has been read in.")
clad = hdf2dict('macro421_Zry__600K.h5')     # INPUT
print(f"File 'macro421_Zry__600K.h5' has been read in.")
cool  = hdf2dict('macro421_H2OB__600K.h5')   # INPUT
print(f"File 'macro421_H2OB__600K.h5' has been read in.")

# Number of energy groups
ng = fuel["ng"]

#--------------------------------------------------------------------------
# Number of nodes
#g = {}
g['nNodesX'] = 10  # INPUT
g['nNodesY'] = 2   # INPUT

# Define the mesh step, nodes coordinates, and node volumes
g['delta'] = 0.2  # cm
volume = np.ones((g['nNodesX'], g['nNodesY'])) * g['delta']**2
volume[[0, -1], :] /= 2
volume[:, [0, -1]] /= 2

# Define the material for each node (0 is coolant, 1 is cladding, 2 is fuel)
mat = np.array([[2, 2, 2, 2, 2, 1, 0, 0, 0, 0],
                [2, 2, 2, 2, 2, 1, 0, 0, 0, 0]])

#--------------------------------------------------------------------------
# Path to Lebedev quadrature function:
path_to_lebedev = os.path.join('..', '00.Lebedev')
# Number of discrete ordinates, an even integer
g['N'] = 110  # INPUT


# Get leb["x"], leb["y"] and leb["z"] values for the g.N base points on a unit sphere
# as well as the associated weights leb["w"] (the unit sphere area corresponding
# to the base points, sum up to 4*np.pi) using the Lebedev quadrature rules.
#from getLebedevSphere import getLebedevSphere  # Assuming the function is available
leb = getLebedevSphere(g['N'])
g['muX'] = leb['x']
g['muY'] = leb['y']
g['muZ'] = leb['z']
g['W'] = leb['w']

# Find the reflective directions for X, Y, and Z directions
g['nRefX'] = np.zeros(g['N'], dtype=int)
g['nRefY'] = np.zeros(g['N'], dtype=int)
g['nRefZ'] = np.zeros(g['N'], dtype=int)

# Find the reflective directions for X, Y, and Z directions
for n in range(g['N']):
    for nn in range(g['N']):
        if np.allclose(g['muX'][nn], -g['muX'][n]) and np.allclose(g['muY'][nn], g['muY'][n]) and np.allclose(g['muZ'][nn], g['muZ'][n]):
            g['nRefX'][n] = nn
        if np.allclose(g['muY'][nn], -g['muY'][n]) and np.allclose(g['muX'][nn], g['muX'][n]) and np.allclose(g['muZ'][nn], g['muZ'][n]):
            g['nRefY'][n] = nn
        if np.allclose(g['muZ'][nn], -g['muZ'][n]) and np.allclose(g['muX'][nn], g['muX'][n]) and np.allclose(g['muY'][nn], g['muY'][n]):
            g['nRefZ'][n] = nn


File 'macro421_UO2_03__900K.h5' has been read in.
File 'macro421_Zry__600K.h5' has been read in.
File 'macro421_H2OB__600K.h5' has been read in.


In [36]:
ans = fuel["sig2_G"]["sparse_Sig2"]
ans

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.04629092e-10, 0.00000000e+00, 0.00000000e+00]])

In [37]:
fuel["sig2_G"]["sparse_Sig2"][420, 417]

8.041752168897633e-08

In [38]:
#--------------------------------------------------------------------------
# Scattering source anisotropy: 0 -- P0 (isotropic), 1 -- P1
g['L'] = 0  # INPUT
# Initialize the 'R' key in the 'g' dictionary
g['R'] = {}
# Calculate spherical harmonics for every ordinate
for n in range(g['N']):
    g['R'][n] = np.zeros((2 * g['L'] + 1, 2 * g['L'] + 1))

    for jLgn in range(g['L'] + 1):
        for m in range(-jLgn, jLgn + 1):
            if jLgn == 0 and m == 0:
                g['R'][n][jLgn, jLgn + m] = 1
            elif jLgn == 1 and m == -1:
                g['R'][n][jLgn, jLgn + m] = g['muZ'][n]
            elif jLgn == 1 and m == 0:
                g['R'][n][jLgn, jLgn + m] = g['muX'][n]
            elif jLgn == 1 and m == 1:
                g['R'][n][jLgn, jLgn + m] = g['muY'][n]

#--------------------------------------------------------------------------
# Construct the cross sections
SigA, SigP, chi, SigT = np.zeros((10, 2, 421)), np.zeros((10, 2, 421)), np.zeros((10, 2, 421)), np.zeros((10, 2, 421))
Sig2 = np.zeros((10, 2, 421, 421))
SigS = np.zeros((jLgn+1, 10, 2, 421, 421))
for iy in range(g['nNodesY']):
    for ix in range(g['nNodesX']):
        if mat[iy, ix] == 2:  # fuel
            SigA[ix, iy] = fuel['SigF'] + fuel['SigC'] + fuel['SigL'] + np.sum(fuel["sig2_G"]["sparse_Sig2"], axis=1)
            for jLgn in range(g['L'] + 1):
                SigS[jLgn][ix, iy] = fuel['sigS_G'][f"sparse_SigS[{jLgn}]"]
            Sig2[ix, iy] = fuel["sig2_G"]["sparse_Sig2"]
            SigP[ix, iy] = fuel['SigP']
            chi[ix, iy] = fuel['chi']
        elif mat[iy, ix] == 1:  # cladding
            SigA[ix, iy] = clad['SigF'] + clad['SigC'] + clad['SigL'] + np.sum(clad["sig2_G"]["sparse_Sig2"], axis=1)
            for jLgn in range(g['L'] + 1):
                SigS[jLgn][ix, iy] = clad['sigS_G'][f"sparse_SigS[{jLgn}]"]
            Sig2[ix, iy] = clad["sig2_G"]["sparse_Sig2"]
            SigP[ix, iy] = clad['SigP']
            chi[ix, iy] = clad['chi']
        elif mat[iy, ix] == 0:  # coolant
            SigA[ix, iy] = cool['SigF'] + cool['SigC'] + cool['SigL'] + np.sum(cool["sig2_G"]["sparse_Sig2"], axis=1)
            for jLgn in range(g['L'] + 1):
                SigS[jLgn][ix, iy] = cool['sigS_G'][f"sparse_SigS[{jLgn}]"]
            Sig2[ix, iy] = cool["sig2_G"]["sparse_Sig2"]
            SigP[ix, iy] = cool['SigP']
            chi[ix, iy] = cool['chi']

        # Total cross section
        SigT[ix, iy] = SigA[ix, iy] + np.sum(SigS[0][ix, iy], axis=1)

#--------------------------------------------------------------------------
# Count the number of equations
nEq = 0
for iy in range(1, g['nNodesY'] + 1):
    for ix in range(1, g['nNodesX'] + 1):
        for n in range(1, g['N'] + 1):
            if g['muZ'][n - 1] >= 0 and not (ix == 1 and g['muX'][n - 1] > 0) and not   \
                (ix == g['nNodesX'] and g['muX'][n - 1] < 0) and not (iy == 1 and       \
                g['muY'][n - 1] > 0) and not (iy == g['nNodesY'] and g['muY'][n - 1] < 0):
                nEq = nEq + ng



In [39]:
g.keys()

dict_keys(['aFlow', 'areaHX', 'clad', 'cool', 'dHyd', 'dz0', 'dzGasPlenum', 'fuel', 'gap', 'nz', 'vGasCentralVoid', 'vGasGap', 'vGasPlenum', 'volFlow', 'nNodesX', 'nNodesY', 'delta', 'N', 'muX', 'muY', 'muZ', 'W', 'nRefX', 'nRefY', 'nRefZ', 'L', 'R'])

In [40]:
def convertV1(solution):
    ng = 421
    # Define the cell array for angular fluxes
    fi = np.zeros((ng, g['N'], g['nNodesX'], g['nNodesY']))
    #solution = np.ones(261020)  # Assuming 261020 elements in the solution vector
    flux = solution.reshape(ng, -1)
    nEq = 0
    for iy in range(1, g['nNodesY'] + 1):
        for ix in range(1, g['nNodesX'] + 1):
            for n in range(1, g['N'] + 1):
                if g['muZ'][n - 1] >= 0 and not (ix == 1 and g['muX'][n - 1] > 0) and not \
                (ix == g['nNodesX'] and g['muX'][n - 1] < 0) and not \
                (iy == 1 and g['muY'][n - 1] > 0) and not \
                (iy == g['nNodesY'] and g['muY'][n - 1] < 0):
                    fi[:, n - 1, ix - 1, iy - 1] = flux[:, nEq]
                    nEq += 1

    for n in range(1, g['N'] + 1):
        if g['muZ'][n - 1] < 0:
            fi[:, n - 1] = fi[:, g['nRefZ'][n - 1] - 1]

    # Boundary conditions
    for n in range(1, g['N'] + 1):
        if g['muX'][n - 1] > 0:
            fi[:, n - 1, 0, :] = fi[:, g['nRefX'][n - 1] - 1, 0, :]
        if g['muX'][n - 1] < 0:
            fi[:, n - 1, g['nNodesX'] - 1, :] = fi[:, g['nRefX'][n - 1] - 1, g['nNodesX'] - 1, :]

    for n in range(1, g['N'] + 1):
        if g['muY'][n - 1] > 0:
            fi[:, n - 1, :, 0] = fi[:, g['nRefY'][n - 1] - 1, :, 0]
        if g['muY'][n - 1] < 0:
            fi[:, n - 1, :, g['nNodesY'] - 1] = fi[:, g['nRefY'][n - 1] - 1, :, g['nNodesY'] - 1]
   
    return fi

fi1 = convertV1(np.ones(nEq))
print(fi1[:, 109, 9, 1])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [41]:
def convert(solution):
    ng = 421
    # Define the cell array for angular fluxes
    fi = np.zeros((ng, g['N'], g['nNodesX'], g['nNodesY']))
    #solution = np.ones(261020)  # Assuming 261020 elements in the solution vector
    flux = solution.reshape(ng, -1)
    nEq = 0
    for iy in range(g['nNodesY']):
        for ix in range(g['nNodesX']):
            for n in range(g['N']):
                if g['muZ'][n] >= 0 and not (ix == 0 and g['muX'][n] > 0) and not \
                (ix == g['nNodesX'] - 1 and g['muX'][n] < 0) and not \
                (iy == 0 and g['muY'][n] > 0) and not \
                (iy == g['nNodesY'] - 1 and g['muY'][n] < 0):
                    fi[:, n, ix, iy] = flux[:, nEq]
                    nEq += 1

    for n in range(g['N']):
        if g['muZ'][n] < 0:
            fi[:, n] = fi[:, g['nRefZ'][n]]

    # Boundary conditions
    for n in range(g['N']):
        if g['muX'][n] > 0:
            fi[:, n, 0, :] = fi[:, g['nRefX'][n], 0, :]
        if g['muX'][n] < 0:
            fi[:, n, g['nNodesX'] - 1, :] = fi[:, g['nRefX'][n], g['nNodesX'] - 1, :]

    for n in range(g['N']):
        if g['muY'][n] > 0:
            fi[:, n, :, 0] = fi[:, g['nRefY'][n], :, 0]
        if g['muY'][n] < 0:
            fi[:, n, :, g['nNodesY'] - 1] = fi[:, g['nRefY'][n], :, g['nNodesY'] - 1]
   
    return fi

fi = convert(np.ones(nEq))
print(fi[:, 109, 9, 1])


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [42]:
nEq

261020

In [43]:
keff = []
residual = []

# Number of outer iterations
numIter = 200  # INPUT

# Set the initial flux equal 1.
solution = np.ones(nEq)

# Main iteration loop
for nIter in range(1, numIter + 1):
    #-----------------------------------------------------------------------
    # Make a guess for the solution
    # Just take the solution from the previous iteration as a guess
    guess = solution.copy()
    #-----------------------------------------------------------------------
    # Convert 1D guess vector to the array of angular flux fi
    fi = convert(guess)
    #-----------------------------------------------------------------------
    fiL = np.zeros((g['nNodesX'], g['nNodesY'], ng, g['L'] + 1, 2 * g['L'] + 1))
    FI = np.zeros((g['nNodesX'], g['nNodesY'], ng))

    for iy in range(1, g['nNodesY'] + 1):
        for ix in range(1, g['nNodesX'] + 1):
            for jLgn in range(g['L'] + 1):
                for m in range(-jLgn, jLgn + 1):
                    SUM = np.zeros(ng)
                    for n in range(g['N']):
                        SUM += fi[:, n, ix - 1, iy - 1] * g['R'][n][jLgn, jLgn + m] * g['W'][n]
                    fiL[ix - 1, iy - 1, :, jLgn, jLgn + m] = SUM
            FI[ix - 1, iy - 1, :] = fiL[ix - 1, iy - 1, :, 0, g['L']]



### Some Extremely weird difference in matrix multplication compared to MATLAB

Feels like I am going insane
![convert notebook to web app](https://i.kym-cdn.com/photos/images/newsfeed/001/818/459/ba2.png)


In [44]:
pRate = 0
aRate = 0
ans1 = np.zeros((10,421))
ans2 = np.zeros((10,421))
ans3 = np.zeros((10, 2))
for iy in range(g['nNodesY']):
    for ix in range(g['nNodesX']):
        pRate += (SigP[ix, iy] + 2 * np.sum(Sig2[ix, iy, :], axis = 1)) @ FI[ix, iy] * volume[ix, iy]
        #        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The exact point where everything goes to shit
        # Best theory at the moment is that floating point errors start to accumulate a will start causing noticable 
        # differences in final output
        aRate += SigA[ix, iy] @ FI[ix, iy] * volume[ix, iy]
        #print("pRate", pRate, "\naRate =", aRate)
#print(sp.sparse.coo_matrix(2 * np.sum(Sig2[ix, iy, :], axis = 1)))
print("aRate", aRate, "\npRate =", pRate)
keff.append(pRate / aRate)
print(f'keff = {keff[-1]:9.5f} #nOuter = {nIter:3}', end=' ')


aRate 242.61850494941638 
pRate = 221.18608974808708
keff =   0.91166 #nOuter = 200 

In [96]:
import numba as nb
@nb.njit
def matmul(vector1, vector2):
    if vector1.ndim != 1 or vector2.ndim != 1:
        raise ValueError("Both inputs must be 1-dimensional arrays.")

    # Get the lengths of the vectors
    m = len(vector1)
    n = len(vector2)

    # Create a zero-filled 2D array of size m x n
    result = np.zeros((m, n))

    # Perform matrix multiplication (dot product) element-wise
    for i in range(m):
        for j in range(n):
            result[i, j] = vector1[i] * vector2[j]

    return result

# Example usage:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
result = matmul(vector1, vector2)
print(result)


[[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]]


In [105]:
print((matmul(chi[0, 0], SigP[0, 0]) @  FI[0, 0]).shape)
print(matmul(chi[0, 0], SigP[0, 0]) @  FI[0, 0])

(421,)
[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0

In [107]:
2 * np.dot(Sig2[ix, iy], FI[ix, iy])

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [45]:
#-----------------------------------------------------------------------
# Calculate fission, (n,2n) and scattering neutron sources
# Initialize the total neutron source vector and nEq
nEq = 0
q2 = np.zeros(ng)
qT_list = np.zeros(ng)

for iy in range(g["nNodesY"]):
    for ix in range(g["nNodesX"]):
        # Fission source (1/s-cm3-steradian)
        qF = matmul(chi[ix, iy], SigP[ix, iy]) @ FI[ix, iy] / keff[-1] / (4*np.pi)

        # Isotropic source from (n,2n) (1/s-cm3-steradian)
        q2 = 2 * np.dot(Sig2[ix, iy].T, FI[ix, iy]) / (4*np.pi)

        for n in range(g["N"]):
            if g["muZ"][n] >= 0 and not ((ix == 0 and g["muX"][n] > 0) or (ix == g["nNodesX"] - 1 and g["muX"][n] < 0) or
                                         (iy == 0 and g["muY"][n] > 0) or (iy == g["nNodesY"] - 1 and g["muY"][n] < 0)):
                # Scattering source (1/s-cm3-steradian), isotropic (g.L = 0) or anisotropic (g.L > 0)
                qS = np.zeros(ng)
                for jLgn in range(g["L"] + 1):
                    SUM = np.zeros(ng)
                    for m in range(-jLgn, jLgn + 1):
                        SUM += fiL[ix, iy][:, 1+jLgn, (1+jLgn) + m] * g.R[n][1+jLgn, (1+jLgn) + m]
                    qS += (2*jLgn + 1) * np.dot(SigS[1+jLgn][ix, iy].T, SUM) / (4*np.pi)

                nEq += 1
                # Right-hand side is a total neutron source:
                qT_list.append(qF + q2 + qS)

# Convert the list of qT to a numpy array
qT = np.array(qT_list)

# Reshape qT into a column vector
RHS = qT.reshape(-1, 1)


(10, 2, 421) (10, 2, 421, 421) (10, 2, 421) (10, 2)


In [82]:
chi[0,0].reshape(-1,1).shape

(421, 1)

In [101]:
np.matmul((chi[0, 0]).T, SigP[0, 0].T)

0.021803736710489293

In [90]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Perform matrix multiplication (dot product)
result = vector1.reshape(-1,1)@ vector2.reshape(-1,1).T # or: result = vector1.dot(vector2)

print(result)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


[[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]]


In [46]:
pRate = 0
aRate = 0
tmp1 = np.zeros((10,421))
tmp2 = np.zeros((421, 10))
tmp3 = np.zeros((10, 2))
tmp4 = np.zeros((10, 2))

for iy in range(g['nNodesY']):
    for ix in range(g['nNodesX']):
        tmp1[ix, :] = (SigP[ix, iy] + 2 * np.sum(Sig2[ix, iy, :], axis = 1))    #<--- The exact point where everything goes to shit
        tmp2[:, ix] = FI[ix, iy] * volume[ix, iy]                               # Best theory at the moment is that floating point 
        tmp3[ix, iy] = tmp1[ix, :] @ tmp2[:, ix]                                # errors start to accumulate a will start causing noticable differences in final output
        tmp4[ix, iy] = (SigP[ix, iy] + 2 * np.sum(Sig2[ix, iy, :], axis = 1)) @ FI[ix, iy] * volume[ix, iy]
        pRate += (SigP[ix, iy] + 2 * np.sum(Sig2[ix, iy, :], axis = 1)) @ FI[ix, iy] * volume[ix, iy]
        aRate += SigA[ix, iy] @ FI[ix, iy] * volume[ix, iy]
        #print("pRate", pRate, "\naRate =", aRate)

tmp3

array([[1.22563142e+01, 1.22563142e+01],
       [2.45126285e+01, 2.45126285e+01],
       [2.45126285e+01, 2.45126285e+01],
       [2.45126285e+01, 2.45126285e+01],
       [2.45126285e+01, 2.45126285e+01],
       [2.86116442e-01, 2.86116442e-01],
       [2.86356251e-05, 2.86356251e-05],
       [2.86356251e-05, 2.86356251e-05],
       [2.86356251e-05, 2.86356251e-05],
       [1.43178126e-05, 1.43178126e-05]])

In [64]:
sprint(Sig2[0,0,403, 92])

  (0, 0)	4.14859867537182e-11


In [48]:
# Specify the file path where you want to save the CSV file
file_path1 = 'tmp1_data.csv'
file_path2 = 'tmp2_data.csv'
# Save the NumPy array to the CSV file
np.savetxt(file_path1, tmp1, delimiter=',', fmt='%.18e')
np.savetxt(file_path2, tmp2, delimiter=',', fmt='%.18e')

In [49]:
type(tmp1[0,0])

numpy.float64

In [50]:
# Initialize ans3 array with zeros
ans3 = np.zeros((g["nNodesX"], g["nNodesY"]))

for iy in range(1):
    for ix in range(1):
        sprint(np.sum(Sig2[ix, iy].T, axis=1))
        ans1 = (SigP[ix, iy] + 2 * np.sum(Sig2[ix, iy], axis=1) )
        ans2 = FI[ix, iy] * volume[ix, iy]
        
        # Perform element-wise multiplication and store the result in a separate matrix
        result_matrix = ans1 * ans2
        
        # Assign the sum of the result_matrix to ans3(ix, iy)
        ans3[ix, iy] = np.sum(result_matrix)

# Print the resulting matrix
print(ans3)


  (0, 92)	1.8078804379962786e-10
  (0, 93)	1.2916540794909468e-10
  (0, 94)	1.6211503630235887e-10
  (0, 95)	6.726191150420666e-10
  (0, 96)	2.4982993002262494e-10
  (0, 97)	4.2637646440390806e-10
  (0, 98)	7.010613126723046e-10
  (0, 99)	3.1388892570502466e-10
  (0, 100)	3.267007369883545e-10
  (0, 101)	3.395125277942363e-10
  (0, 102)	3.523242953302906e-10
  (0, 103)	2.1754424127142036e-10
  (0, 104)	1.703138260882311e-09
  (0, 105)	2.0233599111815065e-09
  (0, 106)	2.0216617340945985e-09
  (0, 107)	3.79298429800596e-09
  (0, 108)	1.1006447956525407e-09
  (0, 109)	2.9158955607775786e-09
  (0, 110)	2.6630358971331023e-09
  (0, 111)	2.1508508235143403e-09
  (0, 112)	2.4268371227457837e-09
  (0, 113)	3.2900071802572124e-09
  (0, 114)	3.878120582103752e-09
  (0, 115)	6.293677035410765e-09
  (0, 116)	2.215859206281051e-09
  :	:
  (0, 394)	0.0005792133553345007
  (0, 395)	0.0018860094677063107
  (0, 396)	0.0020017285926744116
  (0, 397)	0.0017724902494350861
  (0, 398)	0.001897339111149606

In [51]:
SigP[0, 0] + 2 * np.sum(Sig2[ix, iy], axis=1)

array([2.20927333e+01, 9.55351058e+00, 6.71655012e+00, 5.67447720e+00,
       5.05817688e+00, 4.56054516e+00, 3.99790274e+00, 3.51992664e+00,
       3.17812933e+00, 2.80798823e+00, 2.46867826e+00, 2.08096493e+00,
       1.74832817e+00, 1.21042565e+00, 9.46811464e-01, 8.29612632e-01,
       7.15479725e-01, 6.32683204e-01, 5.69103435e-01, 5.18589254e-01,
       4.77306835e-01, 4.43118653e-01, 3.96750256e-01, 3.48792747e-01,
       3.17962718e-01, 3.01585555e-01, 2.99022396e-01, 3.08862769e-01,
       3.23370139e-01, 3.26671180e-01, 3.08272977e-01, 2.75392737e-01,
       2.40830332e-01, 2.11405091e-01, 1.79065954e-01, 1.50258036e-01,
       1.31478392e-01, 1.18468346e-01, 1.11057164e-01, 1.07068493e-01,
       1.02242786e-01, 9.74571211e-02, 9.45183518e-02, 9.34303569e-02,
       9.46510074e-02, 9.74926556e-02, 1.00783313e-01, 1.05541091e-01,
       1.12217055e-01, 1.18340859e-01, 1.22511266e-01, 1.27187275e-01,
       1.32376746e-01, 1.38066801e-01, 1.44226693e-01, 1.50725962e-01,
      

In [52]:
sprint(np.sum(Sig2[ix, iy], axis=1))

  (0, 399)	2.496197186268405e-06
  (0, 400)	4.629222435686947e-05
  (0, 401)	0.00014313686447877744
  (0, 402)	0.00037337036823173404
  (0, 403)	0.0021252190335918596
  (0, 404)	0.0049765531094048965
  (0, 405)	0.013994310739662875
  (0, 406)	0.027979502556078995
  (0, 407)	0.03958158280350837
  (0, 408)	0.04748440000637064
  (0, 409)	0.052046160105849275
  (0, 410)	0.05361748875584749
  (0, 411)	0.055709822217913485
  (0, 412)	0.05938500930773191
  (0, 413)	0.061552301764683744
  (0, 414)	0.0632544128929421
  (0, 415)	0.06503463969661297
  (0, 416)	0.051804381072003435
  (0, 417)	0.0381001684407881
  (0, 418)	0.027458697611168297
  (0, 419)	0.018401370382278296
  (0, 420)	0.013292062543113924


In [53]:
tmp1[:, 0]
tmp2[]

SyntaxError: invalid syntax (735580175.py, line 2)